apiVersion: batch/v1
kind: Job
metadata:
  name: post-migration
spec:
  template:
    spec:
      containers:
        - name: post
          image: ados1991/post:1.0.2
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: user

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password

            - name: DATABASE_SERVICE_HOST
              value: postgres-service

            - name: DATABASE_NAME
              value: post_db
      restartPolicy: Never
  backoffLimit: 5
